Simplify build instructions: Mention libgmock-dev, sysinternalsebpf packages
Sysinternals/SysmonForLinux pull request #41
Opened 2021-11-04 18:01 UTC by hillu

On my Ubuntu 20.04 VM it was not necessary to run `make` inside the
installed googletest package. Installing libgmock-dev was sufficient.

2021-11-29 10:39 UTC, kesheldr requested changes
I don't think this works on Ubuntu 18.04 though, as the libgmock-dev package isn't available. Maybe rework the change so that it makes it clear those instructions are for Ubuntu 20.04 and later only, and retain the old for 18.04?

2021-11-29 23:10 UTC, hillu commented
I tried investigating whether there's another way, but no luck so far. The current set of instructions does not work on Ubuntu 18.04 anyhow. The monodevelop package seems to be broken, one of its dependencies wants newer GLIB than what is available, even via backports.
```
 mono-devel : Depends: libglib2.0-0 (>= 2.56.4) but 2.56.1-2ubuntu1 is to be installed
```

2021-11-30 11:14 UTC, kesheldr commented
Hello @hillu 

I find that odd; to check I just installed a fresh Ubuntu 18.04 on Azure and followed the instructions to the letter and it worked as expected. Colleagues have done similar with standard Ubuntu 18.04 in HyperV. Can I check that you installed the Microsoft key and repo, and did a full apt update?

2021-11-30 19:00 UTC, hillu commented
Oh, I am sorry, I just noticed that a newer libglib2.0-0 package is available via the `bionic-security` repository. My chroot that I use with schroot, sbuild (old Debian Developer habits don't die) did not contain that. Now let me get back to what I was trying to do…

2021-11-30 19:46 UTC, hillu commented
@kesheldr I have updated the instructions.

2021-12-07 23:35 UTC, hillu commented
@kesheldr Would you mind having another look?

2021-12-08 09:29 UTC, kesheldr approved these changes
Yep that's great! Thanks for doing this.

2021-12-08 09:29 UTC, kesheldr commented
I'm sorry I missed your update.

2021-12-08 09:29 UTC, merged